Add CRUD functionality for managing purchasing history
Joseph-Ramon-Lucas/PennyPincher pull request #3
Opened 2024-12-21 18:28 UTC by EricNguyen-B

2024-12-22 04:53 UTC, Joseph-Ramon-Lucas commented
Would love to review with you in the upcoming days!

2025-01-02 22:38 UTC, Joseph-Ramon-Lucas requested changes
All features function as expected.
Please take a look at some of the comments for enhancements / optimizations.

2025-01-02 22:38 UTC, Joseph-Ramon-Lucas commented on PennyPincher.API/PennyPincher/Controllers/LogHistoryController.cs
> +            };
I believe you may not need to create a new UpdateDto object to cast from your regular Dto Object if these models can relate to each other via inheritance

2025-01-05 21:22 UTC, EricNguyen-B commented on PennyPincher.API/PennyPincher/Models/ItemDto.cs
> +        Takeout = 5
Hmm I did not know that C# already compiles it down to an integer list. Perhaps having it explicitly assigned allows for better readability for such a lengthy list of size 5 😊

2025-01-05 22:20 UTC, EricNguyen-B commented on PennyPincher.API/PennyPincher/Models/ItemForUpdateDto.cs
> +        [Required(ErrorMessage = "Price is required for item creation")]
Yeah that should not happen. 

From my understanding if you do include any field of a object body, then it will default to 0 value. I understand this for the Post endpoint where we're using the `ItemDto` object with an optional price field, but this should be avoided with the `[Required]` annotation in the Put endpoint because it uses `ItemForUpdate` object. 

I'll note this and investigate for the next iteration for now.

2025-01-05 22:22 UTC, EricNguyen-B commented on PennyPincher.API/PennyPincher/Models/ItemForUpdateDto.cs
> +        [Required(ErrorMessage = "Price is required for item creation")]
But I can see why the `[Required]` annotation never triggers such a error response because we technically get a non-null price value of `0`.

2025-01-05 22:30 UTC, EricNguyen-B commented on PennyPincher.API/PennyPincher/Controllers/LogHistoryController.cs
> +        public ActionResult<List<ItemDto>> GetAllItems()
I think I will instead add another endpoint specifically for getting all items of a category type than having it an optional parameter. The idea is to enforce single responsibility principle.

2025-01-05 22:33 UTC, EricNguyen-B commented on PennyPincher.API/PennyPincher/Controllers/LogHistoryController.cs
> +            }
The intention was to error check the`ModelState` to see if the `ApplyTo` method was successful in its update operation. Theoretically, `ModelState` should be fine because we did not affect it at all until we execute `ApplyTo`, in which case we check `ModelState` after the action.

2025-01-08 16:13 UTC, Joseph-Ramon-Lucas commented on PennyPincher.API/PennyPincher/Models/ItemForUpdateDto.cs
> +        [Required(ErrorMessage = "Price is required for item creation")]
Even if this model's annotation doesn't trigger, I think it will be a good practice to have a safe guard in the event where somewhere in the future, it can add extra type safety.
I also did the same with my cashflow models.

2025-01-08 16:18 UTC, Joseph-Ramon-Lucas commented on PennyPincher.API/PennyPincher/Program.cs
> +
Glad this annoying whitespace was resolved 😆

2025-01-08 16:45 UTC, Joseph-Ramon-Lucas approved these changes
Overall good changes to the API for `LogHistory`
Supports all expected CRUD endpoints and functions.

I would make that little change to the `Delete` endpoint, then we're good to go

2025-01-08 16:45 UTC, Joseph-Ramon-Lucas commented on PennyPincher.API/PennyPincher/Controllers/LogHistoryController.cs
> +            ItemDto item = ItemsDataStore.Current.Items.FirstOrDefault(i => i.Id == itemToDelete.Id);
This is a subtle change, but still important.
`itemId` is not used in the body of the function `DeleteItem()`
This function is only searching for an item in the list via the `itemToDelete` object passed in.

I would model this function off the `GetItem(int itemId)` endpoint for consistency.
Otherwise, I would remove the parameter `itemId` in the Http handler.

2025-01-11 14:05 UTC, merged